language: php

php: 
  - 5.3
  - 5.4

before_script: 
  - mysql -e 'create database fabbookTest;'
  - composer install
  - php app/console doctrine:schema:create
  - php app/console doctrine:fixtures:load --env=test --no-interaction
script: phpunit -c app/
