language: php

php: 
  - 5.3
  - 5.4

before_script: 
  - mysql -e 'create database fabbook;'
  - composer install
  - php app/console doctrine:schema:create
  - php app/console doctrine:fixtures:load
script: phpunit -c app/
