CREATE TABLE ArticleBlog (id INT AUTO_INCREMENT NOT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, title VARCHAR(255) NOT NULL, subtitle VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, author VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB;
CREATE TABLE articleblog_tag (articleblog_id INT NOT NULL, tag_id INT NOT NULL, INDEX IDX_9F769C4349140E94 (articleblog_id), INDEX IDX_9F769C43BAD26311 (tag_id), PRIMARY KEY(articleblog_id, tag_id)) ENGINE = InnoDB;
CREATE TABLE Tag (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB;
ALTER TABLE articleblog_tag ADD CONSTRAINT FK_9F769C4349140E94 FOREIGN KEY (articleblog_id) REFERENCES ArticleBlog(id) ON DELETE CASCADE;
ALTER TABLE articleblog_tag ADD CONSTRAINT FK_9F769C43BAD26311 FOREIGN KEY (tag_id) REFERENCES Tag(id) ON DELETE CASCADE;

CREATE TABLE tag_articleblog (tag_id INT NOT NULL, articleblog_id INT NOT NULL, INDEX IDX_3A81123BAD26311 (tag_id), INDEX IDX_3A8112349140E94 (articleblog_id), PRIMARY KEY(tag_id, articleblog_id)) ENGINE = InnoDB;
ALTER TABLE tag_articleblog ADD CONSTRAINT FK_3A81123BAD26311 FOREIGN KEY (tag_id) REFERENCES Tag(id) ON DELETE CASCADE;
ALTER TABLE tag_articleblog ADD CONSTRAINT FK_3A8112349140E94 FOREIGN KEY (articleblog_id) REFERENCES ArticleBlog(id) ON DELETE CASCADE;

DROP TABLE tag_articleblog;

CREATE TABLE ArticleBlog_tags (articleblog_id INT NOT NULL, tag_id INT NOT NULL, INDEX IDX_618A506349140E94 (articleblog_id), INDEX IDX_618A5063BAD26311 (tag_id), PRIMARY KEY(articleblog_id, tag_id)) ENGINE = InnoDB;
ALTER TABLE ArticleBlog_tags ADD CONSTRAINT FK_618A506349140E94 FOREIGN KEY (articleblog_id) REFERENCES ArticleBlog(id) ON DELETE CASCADE;
ALTER TABLE ArticleBlog_tags ADD CONSTRAINT FK_618A5063BAD26311 FOREIGN KEY (tag_id) REFERENCES Tag(id) ON DELETE CASCADE;
DROP TABLE articleblog_tag;
