<?php

namespace Fabfoto\GalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findLastNews($max)
    {
        return $this->getQueryOrderBydate($max)->execute();
    }
    public function getQueryOrderBydate($max = null)
    {
        $query = $this->createQueryBuilder('n')
                ->add('orderBy', 'n.createdAt DESC');
        if ($max) {
            $query->setMaxResults($max);
        }

        return $query->getQuery();
    }

}
