<?php

namespace Fabfoto\GalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleBlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleBlogRepository extends EntityRepository
{
    public function getByTag($tag)
    {
        $tags = array($tag);

        return $this->findByTags($tags);
    }
    public function getByTags(array $tags)
    {

        //return $qb->getQuery()->getResult();
    }
    public function search($keywords)
    {
        return $this
                ->createQueryBuilder('s')
                ->where('s.title LIKE :keywords AND s.isPublished = TRUE')
                ->setParameter('keywords', sprintf('%%%s%%', $keywords))
                ->getQuery()
                ->execute();
    }
    public function OrderByDate()
    {
        return $this->queryOrderBydate()->execute();
    }
    private function queryOrderBydate()
    {
        return $this->_em
                        ->createQuery('SELECT s FROM FabfotoGalleryBundle:ArticleBlog s ORDER BY s.createdAt DESC');
    }

    public function getQueryOrderByUpdatedAt($max = null)
    {
        $query = $this->createQueryBuilder('n')
                ->add('orderBy', 'n.updatedAt DESC');
        if ($max) {
            $query->setMaxResults($max);
        }

        return $query->getQuery();
    }
}
