parameters:
#    knp_upload.example.class: Knp\UploadBundle\Example
     nbArticle: %fabfoto_gallery.nbArticle% 
     nbAlbum: %fabfoto_gallery.nbAlbum% 

services:
#    knp_upload.example:
#        class: %knp_upload.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


    fabfoto_gallery.picture_uploader:
        class:      Fabfoto\GalleryBundle\Uploader\PictureUploader
        arguments:  [%fabfoto_gallery.picture_directory%]
        
#    fabfoto_gallery.string_tools:
#        class:      Fabfoto\GalleryBundle\StringTools\StringTools
      
        