parameters:
     nbArticle: %fabfoto_gallery.nbArticle%
     nbAlbum: %fabfoto_gallery.nbAlbum%

services:

    fabfoto_gallery.picture_uploader:
        class:      Fabfoto\GalleryBundle\Uploader\PictureUploader
        arguments:  [%fabfoto_gallery.picture_directory%]

    fabfoto_gallery.picture_importer:
        class:      Fabfoto\GalleryBundle\Import\PictureImporter
        arguments:
            - @doctrine.orm.entity_manager
            - @fabfoto_gallery.picture_uploader
            - %fabfoto_gallery.import_directory%
