imports:
    - { resource: config.yml }

doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%Prod
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: ~  
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug     