imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

sensio_framework_extra:
  view:
    annotations: false
framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true
    translator: ~
    

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%


# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    read_from:      %kernel.root_dir%/../www
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport_dev%
    username:  %mailer_user_dev%
    password:  %mailer_password_dev%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

#GalleryBundle Configuration
fabfoto_gallery:
    picture_directory: %upload_directory%
    mailsender: %mail_sender_adress%
    import_directory: %incoming_directory%
    #Element of each last blog and album display in last home page
    nbArticle: 4
    nbAlbum: 2


knp_last_tweets:
    fetcher:
        driver: api
        options:
            cache_name: knp_last_tweets
avalanche_imagine:
    source_root:  %kernel.root_dir%/../www
    web_root:     %kernel.root_dir%/../www
    cache_prefix: media/cache
    driver:       gd
    filters:
        thumb_square:
            type:    thumbnail
            options: { size: [128, 128], mode: outbound }            
        cover:
            type:    thumbnail
            options: { size: [650, 180], mode: outbound }            
        background:
            type:    thumbnail
            options: { size: [1024, 768], mode: inset }            
liip_imagine:
    driver:               gd
    web_root:             %kernel.root_dir%/../www
    data_root:            %kernel.root_dir%/../www
    cache_prefix:         /media/cache
    cache:                web_path
    data_loader:          filesystem
    controller_action:    liip_imagine.controller:filterAction
    formats:              []
    filter_sets:
        thumb_square:
            filters:
                thumbnail: { size: [128, 128], mode: outbound }
        web_view:
            filters:
                relative_resize: { widen: 600 }    # Transforms 50x40 to 40x32
        cover:
            filters:
                thumbnail: { size: [650, 180], mode: outbound } 
        background:
            filters:
                thumbnail: { size: [1024, 768], mode: outbound } 
stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            timestampable: true
            sluggable: true
knp_menu:
    twig: true
admingenerator_generator:
    base_admin_template: FabfotoAdminBundle::base_admin.html.twig
    knp_menu_class: Fabfoto\AdminBundle\Menu\AdminMenu
    use_propel: false
    use_doctrine_orm: true
    use_doctrine_odm: false
admingenerator_user:
    login_template: AdmingeneratorGeneratorBundle::base_login_assetic_less.html.twig
genemu_form:
    tinymce:
        script_url: '/bundles/fabfotogallery/tiny_mce/tiny_mce.js'      
        enabled: true
        theme:   advanced 
    recaptcha:
            public_key:  6LcIEtESAAAAACk_Mc02xR3nwFw5RdnEkkkdwuXm
            private_key: 6LcIEtESAAAAAD1sT0-8wNoxCWmBSecK97wRQA25            
                  
jms_serializer:
    handlers:
        object_based: false
        datetime:
            format: "Y-m-dTH:i:s" # ISO8601
            default_timezone: "UTC" # defaults to whatever timezone set in php.ini or via date_default_timezone_set
        array_collection: true
        form_error: true
        constraint_violation: true

    property_naming:
        separator:  _
        lower_case: true

    metadata:
        cache: file
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"

        # Using auto-detection, the mapping files for each bundle will be
        # expected in the Resources/config/serializer directory.
        #
        # Example:
        # class: My\FooBundle\Entity\User
        # expected path: @MyFooBundle/Resources/config/serializer/Entity.User.(yml|xml|php)
        auto_detection: true

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Fabfoto\UserBundle\Entity\User     
    registration:
        confirmation:
          enabled: true
        form:
            type: fabfoto_user_registration    
exercise_html_purifier:
    default:
        Cache.SerializerPath: '%kernel.cache_dir%/htmlpurifier'
services:
    markup.exercise_html_purifier:
        class: FOS\CommentBundle\Markup\HtmlPurifier
        arguments: [ @exercise_html_purifier.default ]        
fos_comment:
    acl: true
    service:
        acl:
            thread: fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote: fos_comment.acl.vote.roles
        markup: markup.exercise_html_purifier         
    db_driver: orm
    class:
        model:
            comment: Fabfoto\GalleryBundle\Entity\Comment
            thread: Fabfoto\GalleryBundle\Entity\Thread        
    acl_roles:
        comment:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        thread:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        vote:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN         
     