FabfotoAdminBundle:
    resource: "@FabfotoAdminBundle/Controller/"
    type:     annotation
    prefix:   /

FabfotoZendTweetBundle:
    resource: "@FabfotoZendTweetBundle/Controller/"
    type:     annotation
    prefix:   /

_fabfoto:
    resource: "@FabfotoGalleryBundle/Controller/"
    type:     annotation
    prefix:   /
   
_imagine: 
  resource: . 
  type: imagine

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /sonata

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admnin
    
my_barcode_playground:
    resource: "@MopaBarcodeBundle/Resources/config/routing/barcode_playground.yml"
    prefix:   /

#_imagine_thumb_square:
#    pattern: /media/cache/thumb_square/{path}
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
