FabfotoAdminBundle_admin_fabfoto_admin_bundle_Prefix:
    resource: "@FabfotoAdminBundle/Controller/Prefix/"
    type:     admingenerator
    prefix:   /admin/fabfoto_admin_bundle/Prefix

FabfotoZendTweetBundle:
    resource: "@FabfotoZendTweetBundle/Controller/"
    type:     annotation
    prefix:   /

_fabfoto:
    resource: "@FabfotoGalleryBundle/Controller/"
    type:     annotation
    prefix:   /
   
_imagine: 
  resource: . 
  type: imagine
  
my_barcode_playground:
    resource: "@MopaBarcodeBundle/Resources/config/routing/barcode_playground.yml"
    prefix:   /

#_imagine_thumb_square:
#    pattern: /media/cache/thumb_square/{path}
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
