FabfotoI18nBundle:
    resource: "@FabfotoI18nBundle/Controller/"
    type:     annotation
    prefix:   /

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

FabfotoUserBundle:
    resource: "@FabfotoUserBundle/Controller/"
    type:     annotation
    prefix:   /

FabfotoAdminBundle_Cover:
    resource: "@FabfotoAdminBundle/Controller/Cover/"
    type:     admingenerator
    prefix:   /admin/cover
    
FabfotoAdminBundle_Comment:
    resource: "@FabfotoAdminBundle/Controller/Comment/"
    type:     admingenerator
    prefix:   /admin/comment
FabfotoAdminBundle_Portrait:
    resource: "@FabfotoAdminBundle/Controller/Portrait/"
    type:     admingenerator
    prefix:   /admin/portrait
FabfotoAdminBundle_User:
    resource: "@FabfotoAdminBundle/Controller/User/"
    type:     admingenerator
    prefix:   /admin/user
FabfotoAdminBundle_Message:
    resource: "@FabfotoAdminBundle/Controller/Message/"
    type:     admingenerator
    prefix:   /admin/message
FabfotoAdminBundle_Tag:
    resource: "@FabfotoAdminBundle/Controller/Tag/"
    type:     admingenerator
    prefix:   /admin/tag
FabfotoAdminBundle_Author:
    resource: "@FabfotoAdminBundle/Controller/Author/"
    type:     admingenerator
    prefix:   /admin/author
FabfotoAdminBundle_Blog:
    resource: "@FabfotoAdminBundle/Controller/Blog/"
    type:     admingenerator
    prefix:   /admin/blog
FabfotoAdminBundle_News:
    resource: "@FabfotoAdminBundle/Controller/News/"
    type:     admingenerator
    prefix:   /admin/news
FabfotoAdminBundle_Album:
    resource: "@FabfotoAdminBundle/Controller/Album/"
    type:     admingenerator
    prefix:   /admin/album
    
FabfotoAdminBundle_Picture:
    resource: "@FabfotoAdminBundle/Controller/Picture/"
    type:     admingenerator
    prefix:   /admin/picture

_fabfoto:
    resource: "@FabfotoGalleryBundle/Controller/"
    type:     annotation
    prefix:   /
#    prefix:   /{_locale}/
#    defaults:  { _controller: FabfotoI18nBundle:Default:index, _locale: fr }
#    requirements:
#        _locale: en|fr
   
_imagine: 
  resource: . 
  type: imagine

my_barcode_playground:
    resource: "@MopaBarcodeBundle/Resources/config/routing/barcode_playground.yml"
    prefix:   /
console:
    resource: "@CoreSphereConsoleBundle/Resources/config/routing.yml"
    prefix:   /admin
#_imagine_thumb_square:
#    pattern: /media/cache/thumb_square/{path}
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
