knplabs_translator_admin:
    resource: "@KnpTranslatorBundle/Resources/config/routing/edition.yml"
    prefix:   /trans/admin

knplabs_translator:
    resource: "@KnpTranslatorBundle/Resources/config/routing/routing.yml"
    prefix:   /trans

A5sysProjectBundle:
    resource: "@A5sysProjectBundle/Controller/"
    type:     annotation
    prefix:   /