FabfotoAdminBundle_Message:
    resource: "@FabfotoAdminBundle/Controller/Message/"
    type:     admingenerator
    prefix:   /admin/bundle/message
FabfotoAdminBundle_Tag:
    resource: "@FabfotoAdminBundle/Controller/Tag/"
    type:     admingenerator
    prefix:   /admin/bundle/tag
FabfotoAdminBundle_Author:
    resource: "@FabfotoAdminBundle/Controller/Author/"
    type:     admingenerator
    prefix:   /admin/bundle/author
FabfotoAdminBundle_Blog:
    resource: "@FabfotoAdminBundle/Controller/Blog/"
    type:     admingenerator
    prefix:   /admin/bundle/blog
FabfotoAdminBundle_News:
    resource: "@FabfotoAdminBundle/Controller/News/"
    type:     admingenerator
    prefix:   /admin/bundle/news
FabfotoAdminBundle_Album:
    resource: "@FabfotoAdminBundle/Controller/Album/"
    type:     admingenerator
    prefix:   /admin/bundle/album
    
FabfotoAdminBundle_Picture:
    resource: "@FabfotoAdminBundle/Controller/Picture/"
    type:     admingenerator
    prefix:   /admin/bundle/picture

FabfotoZendTweetBundle:
    resource: "@FabfotoZendTweetBundle/Controller/"
    type:     annotation
    prefix:   /

_fabfoto:
    resource: "@FabfotoGalleryBundle/Controller/"
    type:     annotation
    prefix:   /
   
_imagine: 
  resource: . 
  type: imagine
  
my_barcode_playground:
    resource: "@MopaBarcodeBundle/Resources/config/routing/barcode_playground.yml"
    prefix:   /
console:
    resource: "@CoreSphereConsoleBundle/Resources/config/routing.yml"
    prefix:   /admin
#_imagine_thumb_square:
#    pattern: /media/cache/thumb_square/{path}
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
