<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111210224219 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE ArticleBlog (id INT AUTO_INCREMENT NOT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, title VARCHAR(255) NOT NULL, subtitle VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, author VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE articleblog_tag (articleblog_id INT NOT NULL, tag_id INT NOT NULL, INDEX IDX_9F769C4349140E94 (articleblog_id), INDEX IDX_9F769C43BAD26311 (tag_id), PRIMARY KEY(articleblog_id, tag_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Tag (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE articleblog_tag ADD CONSTRAINT FK_9F769C4349140E94 FOREIGN KEY (articleblog_id) REFERENCES ArticleBlog(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE articleblog_tag ADD CONSTRAINT FK_9F769C43BAD26311 FOREIGN KEY (tag_id) REFERENCES Tag(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE articleblog_tag DROP FOREIGN KEY FK_9F769C4349140E94");
        $this->addSql("ALTER TABLE articleblog_tag DROP FOREIGN KEY FK_9F769C43BAD26311");
        $this->addSql("DROP TABLE ArticleBlog");
        $this->addSql("DROP TABLE articleblog_tag");
        $this->addSql("DROP TABLE Tag");
    }
}
