<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120404165101 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE fos_user DROP FOREIGN KEY FK_957A64791226EBF3");
        $this->addSql("DROP INDEX UNIQ_957A64791226EBF3 ON fos_user");
        $this->addSql("ALTER TABLE fos_user DROP portrait_id, DROP mail");
        $this->addSql("ALTER TABLE Portrait ADD user_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE Portrait ADD CONSTRAINT FK_6C3656ADA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id)");
        $this->addSql("CREATE INDEX IDX_6C3656ADA76ED395 ON Portrait (user_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Portrait DROP FOREIGN KEY FK_6C3656ADA76ED395");
        $this->addSql("DROP INDEX IDX_6C3656ADA76ED395 ON Portrait");
        $this->addSql("ALTER TABLE Portrait DROP user_id");
        $this->addSql("ALTER TABLE fos_user ADD portrait_id INT DEFAULT NULL, ADD mail VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD CONSTRAINT FK_957A64791226EBF3 FOREIGN KEY (portrait_id) REFERENCES Portrait(id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_957A64791226EBF3 ON fos_user (portrait_id)");
    }
}
