<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111211130302 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE tag_articleblog");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE tag_articleblog (tag_id INT NOT NULL, articleblog_id INT NOT NULL, INDEX IDX_3A81123BAD26311 (tag_id), INDEX IDX_3A8112349140E94 (articleblog_id), PRIMARY KEY(tag_id, articleblog_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE tag_articleblog ADD CONSTRAINT FK_3A8112349140E94 FOREIGN KEY (articleblog_id) REFERENCES ArticleBlog(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE tag_articleblog ADD CONSTRAINT FK_3A81123BAD26311 FOREIGN KEY (tag_id) REFERENCES Tag(id) ON DELETE CASCADE");
    }
}
