<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111211164059 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE ArticleBlog_tags (articleblog_id INT NOT NULL, tag_id INT NOT NULL, INDEX IDX_618A506349140E94 (articleblog_id), INDEX IDX_618A5063BAD26311 (tag_id), PRIMARY KEY(articleblog_id, tag_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE ArticleBlog_tags ADD CONSTRAINT FK_618A506349140E94 FOREIGN KEY (articleblog_id) REFERENCES ArticleBlog(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE ArticleBlog_tags ADD CONSTRAINT FK_618A5063BAD26311 FOREIGN KEY (tag_id) REFERENCES Tag(id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE articleblog_tag");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE articleblog_tag (articleblog_id INT NOT NULL, tag_id INT NOT NULL, INDEX IDX_9F769C4349140E94 (articleblog_id), INDEX IDX_9F769C43BAD26311 (tag_id), PRIMARY KEY(articleblog_id, tag_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE articleblog_tag ADD CONSTRAINT FK_9F769C4349140E94 FOREIGN KEY (articleblog_id) REFERENCES ArticleBlog(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE articleblog_tag ADD CONSTRAINT FK_9F769C43BAD26311 FOREIGN KEY (tag_id) REFERENCES Tag(id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE ArticleBlog_tags");
    }
}
