generator: admingenerator.generator.doctrine
params:
  model: Fabfoto\GalleryBundle\Entity\Album
  namespace_prefix: Fabfoto
  bundle_name: AdminBundle
  fields: ~

builders:
  list:
    params:
      title: List for AdminBundle
      display: ~
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: Nouvel album
      display: [name, comment]
      actions:
        list: ~
  edit:
    params:
      title: You're editing the object "{{ Album.name }}"
      display: [name, comment]
      actions:
        list: ~
  delete: ~
