generator: admingenerator.generator.doctrine
params:
  model: Fabfoto\GalleryBundle\Entity\Album
  namespace_prefix: Fabfoto
  bundle_name: AdminBundle
  fields:
    category:
      formType: genemu_jquerychosen_entity
      addFormOptions:
        class: "FabfotoGalleryBundle:Category"

builders:
  list:
    params:
      title: List for AdminBundle
      sort: [ createdAt, DESC ]
      display: [name, comment, category, createdAt, slug]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: [name, createdAt, category]
  new:
    params:
      title: Nouvel album
      display: [name, comment, category]
      actions:
        list: ~
  edit:
    params:
      title: You're editing the object "{{ Album.name }}"
      display: [name, comment, category]
      actions:
        list: ~
  delete: ~
