generator: admingenerator.generator.doctrine
params:
  model: Fabfoto\GalleryBundle\Entity\Author
  namespace_prefix: Fabfoto
  bundle_name: AdminBundle
  fields:
    firstname: 
      label: FistName
    description:
      formType: genemu_tinymce
      addFormOptions:
        required: true     
    googleLink:
      label: Google Plus
      addFormOptions:
        required: false
    facebookLink:
      label: Facebook
      addFormOptions:
        required: false      
    gitHubLink:
      label: GitHub
      addFormOptions:
        required: false      
    twitterLink:
      label: Twitter
      addFormOptions:
        required: false      
    phone:
      label: Phone Number
      addFormOptions:
        required: false         
        
builders:
  list:
    params:
      title: List of user
      display: [name, firstname, title, mail]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: [name, firstname, title, mail]
  new:
    params:
      title: New object for AdminBundle
      display: [name, firstname, title, mail, description, googleLink, facebookLink, gitHubLink, twitterLink, phone]
      actions:
        list: ~
  edit:
    params:
      title: You're editing the object "{{ Author.firstname }} {{ Author.name }}"
      display: [name, firstname, title, mail, description, googleLink, facebookLink, gitHubLink, twitterLink, phone]
      actions:
        list: ~
  delete: ~
