generator: admingenerator.generator.doctrine
params:
  model: Fabfoto\GalleryBundle\Entity\ArticleBlog
  namespace_prefix: Fabfoto
  bundle_name: AdminBundle
  fields:
    content:
      formType: genemu_tinymce
      addFormOptions:
        required: false 
    cover:
      formType: genemu_jquerychosen
      addFormOptions:
        class: "FabfotoGalleryBundle:Cover"
        widget: entity
    tags:
      formType: genemu_jquerychosen
      addFormOptions:
        class: "FabfotoGalleryBundle:Tag"
        multiple: true
        required: false
        widget: entity
builders:
  list:
    params:
      title: List of Blog articles
      display: [id,isPublished, createdAt, updatedAt, title, subtitle, author ]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: [ createdAt, updatedAt, title, subtitle, author, isPublished ]
  new:
    params:
      title: New object for AdminBundle
      display: [ isPublished, title, subtitle, content, tags, cover ]
      actions:
        list: ~
  edit:
    params:
      title: You're editing the object "{{ ArticleBlog.title }}"
      display: [ isPublished, title, subtitle, content, tags, cover ]
      actions:
        list: ~
  delete: ~
