generator: admingenerator.generator.doctrine
params:
  model: Fabfoto\GalleryBundle\Entity\Comment
  namespace_prefix: Fabfoto
  bundle_name: AdminBundle
  fields:
    thread:
      formType: genemu_jquerychosen_entity
      addFormOptions:
        class: "FabfotoGalleryBundle:Thread"


builders:
  list:
    params:
      title: List for Comment
      sort: [ createdAt, DESC ]
      display: [body, depth, createdAt, id, thread]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: [thread, createdAt]
  new:
    params:
      title: New object for AdminBundle
      display: ~
      actions:
        list: ~
  edit:
    params:
      title: You're editing the object "{{ Comment.id }}"
      display: ~
      actions:
        list: ~
  delete: ~
