generator: admingenerator.generator.doctrine
params:
  model: Fabfoto\ShoppingListBundle\Entity\Item
  namespace_prefix: Fabfoto
  bundle_name: AdminBundle
  fields: ~

builders:
  list:
    params:
      title: List for AdminBundle
      display: ~
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: New object for AdminBundle
      display: [name, checked, favorite, onlist, quantity]
      actions:
        list: ~
  edit:
    params:
      title: You're editing the object "{{ Item.name }}"
      display: [name, checked, favorite, onlist, quantity]
      actions:
        list: ~
  delete: ~
