generator: admingenerator.generator.doctrine
params:
  model: Fabfoto\ShoppingListBundle\Entity\Item
  namespace_prefix: Fabfoto
  bundle_name: AdminBundle
  fields: ~

builders:
  list:
    params:
      title: TODO Liste Admin
      display: ~
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: New TODO
      display: [name]
      actions:
        list: ~
  edit:
    params:
      title: "{{ Item.name }}"
      display: [name]
      actions:
        list: ~
  delete: ~
