generator: admingenerator.generator.doctrine
params:
  model: Fabfoto\GalleryBundle\Entity\Message
  namespace_prefix: Fabfoto
  bundle_name: AdminBundle
  fields: ~

builders:
  list:
    params:
      title: Liste des messages
      display: ~
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: [sender, subject, createdAt]
  new:
    params:
      title: New object for AdminBundle
      display: ~
      actions:
        list: ~
  edit:
    params:
      title: You're editing the object "{{ Message.subject }}"
      display: ~
      actions:
        list: ~
  delete: ~
