generator: admingenerator.generator.doctrine
params:
  model: Fabfoto\GalleryBundle\Entity\Article
  namespace_prefix: Fabfoto
  bundle_name: AdminBundle
  fields:
    content:
      formType: genemu_tinymce
      addFormOptions:
        required: false
    author:
      formType: genemu_jquerychosen
      addFormOptions:
        class: "FabfotoUserBundle:User"
        widget: entity 
builders:
  list:
    params:
      title: List of News
      sort: [ createdAt, DESC ]
      display: [id, title, subtitle, createdAt, author]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: [ title, subtitle, createdAt, author]
  new:
    params:
      title: New object for AdminBundle
      display: [title, subtitle, content]
      actions:
        list: ~
  edit:
    params:
      title: You're editing the object "{{ Article.title }}"
      display: [title, subtitle, content]
      actions:
        list: ~
  delete: ~
