generator: admingenerator.generator.doctrine
params:
  model: Fabfoto\GalleryBundle\Entity\Picture
  namespace_prefix: Fabfoto
  bundle_name: AdminBundle
  fields:
    album:
      formType: genemu_jquerychosen_entity
      addFormOptions:
        class: "FabfotoGalleryBundle:Album"
    location:
      formType: file
      addFormOptions:
        required: false


builders:
  list:
    params:
      title: List for AdminBundle
      sort: [ createdAt, DESC ]
      display: ~
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: [name, createdAt, album, isBackground]
  new:
    params:
      title: New Picture
      display: [name, location, album, isBackground]
      actions:
        list: ~
  edit:
    params:
      title: Picture "{{ Picture.name }}"
      display: [name, album, isBackground]
      actions:
        list: ~
  delete: ~
