<?php

namespace Fabfoto\TrainTimingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StationRepository extends EntityRepository
{
}
